x-app-base: &app-base
  build: .
  image: lafaom_base_app
  env_file:
    - .env
  volumes:
    - .:/app
  networks:
    - app_network

services:
  # Base de données PostgreSQL
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-lafaom_db}
      POSTGRES_USER: ${POSTGRES_USER:-lafaom_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-lafaom_password}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-lafaom_user} -d ${POSTGRES_DB:-lafaom_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis pour le cache et Celery
  redis:
    image: redis:7.0.8-alpine
    networks:
      - app_network
    restart: unless-stopped

  # Application principale
  app:
    <<: *app-base
    command: /start
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - app-uploads:/app/src/static/uploads
      - app-uploads-2:/app/uploads
    restart: unless-stopped

  # Worker Celery
  celery_worker:
    <<: *app-base
    command: /start-celeryworker
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

  # Scheduler Celery Beat
  celery_beat:
    <<: *app-base
    command: /start-celerybeat
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - celery-beat:/app/celerybeat
    restart: unless-stopped

volumes:
  postgres_data:
  celery-beat:
  app-uploads:
  app-uploads-2:

networks:
  app_network:
    driver: bridge