x-app-base: &app-base
  build: .
  image: lafaom_base_app
  env_file:
    - .env
  volumes:
    - .:/app
  networks:
    - database_network
    - redis_network

services:
  
  redis:
    image: redis:7.0.8-alpine
    networks:
      - redis_network

  celery_worker:
    <<: *app-base
    command: /start-celeryworker
    depends_on:
      - redis

  celery_beat:
    <<: *app-base
    command: /start-celerybeat
    depends_on:
      - redis
    volumes:
      - .:/app
      - celery-beat:/app/celerybeat

  app:
    <<: *app-base
    command: /start
    ports:
      - "7051:8000"
    volumes:
      - .:/app
      - app-uploads:/app/src/static/uploads
      - app-uploads-2:/app/uploads

  # Nouveau service Caddy
  caddy:
    image: caddy:2-alpine
    container_name: lafaom_caddy
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - database_network
    depends_on:
      - app

volumes:
    celery-beat:
    app-uploads:
    app-uploads-2:
    caddy_data:
    caddy_config:

networks:
  
  database_network:
    name: afrolancer_backend_database_network
    external: true
  redis_network: