#!/bin/bash

set -o errexit
set -o nounset

worker_ready() {
    celery -A src.main.celery inspect ping
}

until worker_ready; do
  >&2 echo 'Celery workers not available'
  sleep 1
done
>&2 echo 'Celery workers is available'


# Set the Celery broker URL as an environment variable
export CELERY_BROKER_URL="redis://redis:6379/0;redis://redis:6379/1"
export CELERY_RESULT_BACKEND="redis://redis:6379/0;redis://redis:6379/1"

# Start Celery Flower
exec celery flower \
    --db=/app/flower_db/flower.db \
    --broker="redis://redis:6379/0;redis://redis:6379/1" \
    --state_save_interval=5000 \
    --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"