"""Add missing fields to training_sessions table

Revision ID: 41eb1b4fe5b7
Revises: 07d644ce55f2
Create Date: 2025-10-23 11:28:07.638733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '41eb1b4fe5b7'
down_revision: Union[str, None] = '07d644ce55f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_sessions', sa.Column('center_id', sa.Integer(), nullable=True))
    op.add_column('training_sessions', sa.Column('registration_deadline', sa.Date(), nullable=True))
    op.add_column('training_sessions', sa.Column('available_slots', sa.Integer(), nullable=True))
    op.add_column('training_sessions', sa.Column('moodle_course_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.create_foreign_key(None, 'training_sessions', 'organization_centers', ['center_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training_sessions', type_='foreignkey')
    op.drop_column('training_sessions', 'moodle_course_id')
    op.drop_column('training_sessions', 'available_slots')
    op.drop_column('training_sessions', 'registration_deadline')
    op.drop_column('training_sessions', 'center_id')
    # ### end Alembic commands ###
