"""Add campaign_id to CabinetApplication

Revision ID: 859741f6aaeb
Revises: d776a7c7f4ca
Create Date: 2025-10-08 16:32:51.936897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '859741f6aaeb'
down_revision: Union[str, None] = 'd776a7c7f4ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cabinet_applications', sa.Column('campaign_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'cabinet_applications', 'cabinet_recruitment_campaigns', ['campaign_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cabinet_applications', type_='foreignkey')
    op.drop_column('cabinet_applications', 'campaign_id')
    # ### end Alembic commands ###
