"""Add payment_id to cabinet_applications

Revision ID: 900108de420f
Revises: e8c6d5152d42
Create Date: 2025-10-08 15:57:50.422598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '900108de420f'
down_revision: Union[str, None] = 'e8c6d5152d42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cabinet_applications', sa.Column('payment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'cabinet_applications', 'payments', ['payment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cabinet_applications', type_='foreignkey')
    op.drop_column('cabinet_applications', 'payment_id')
    # ### end Alembic commands ###
