"""Update posts summary field to TEXT

Revision ID: c83490a63e2e
Revises: 03342f8f077a
Create Date: 2025-10-10 18:45:41.607083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'c83490a63e2e'
down_revision: Union[str, None] = '03342f8f077a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'summary',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'summary',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
