"""Add cabinet_application relationship to User

Revision ID: d776a7c7f4ca
Revises: 900108de420f
Create Date: 2025-10-08 16:28:44.901220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'd776a7c7f4ca'
down_revision: Union[str, None] = '900108de420f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
